// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gru/v1/gru.proto

package gruv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dakshjotwani/gru/proto/gru/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GruServiceName is the fully-qualified name of the GruService service.
	GruServiceName = "gru.v1.GruService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GruServiceListSessionsProcedure is the fully-qualified name of the GruService's ListSessions RPC.
	GruServiceListSessionsProcedure = "/gru.v1.GruService/ListSessions"
	// GruServiceGetSessionProcedure is the fully-qualified name of the GruService's GetSession RPC.
	GruServiceGetSessionProcedure = "/gru.v1.GruService/GetSession"
	// GruServiceLaunchSessionProcedure is the fully-qualified name of the GruService's LaunchSession
	// RPC.
	GruServiceLaunchSessionProcedure = "/gru.v1.GruService/LaunchSession"
	// GruServiceKillSessionProcedure is the fully-qualified name of the GruService's KillSession RPC.
	GruServiceKillSessionProcedure = "/gru.v1.GruService/KillSession"
	// GruServiceSendInputProcedure is the fully-qualified name of the GruService's SendInput RPC.
	GruServiceSendInputProcedure = "/gru.v1.GruService/SendInput"
	// GruServiceSuggestSessionNameProcedure is the fully-qualified name of the GruService's
	// SuggestSessionName RPC.
	GruServiceSuggestSessionNameProcedure = "/gru.v1.GruService/SuggestSessionName"
	// GruServiceListProjectsProcedure is the fully-qualified name of the GruService's ListProjects RPC.
	GruServiceListProjectsProcedure = "/gru.v1.GruService/ListProjects"
	// GruServiceUpdateProjectProcedure is the fully-qualified name of the GruService's UpdateProject
	// RPC.
	GruServiceUpdateProjectProcedure = "/gru.v1.GruService/UpdateProject"
	// GruServiceListProfilesProcedure is the fully-qualified name of the GruService's ListProfiles RPC.
	GruServiceListProfilesProcedure = "/gru.v1.GruService/ListProfiles"
	// GruServiceSubscribeEventsProcedure is the fully-qualified name of the GruService's
	// SubscribeEvents RPC.
	GruServiceSubscribeEventsProcedure = "/gru.v1.GruService/SubscribeEvents"
)

// GruServiceClient is a client for the gru.v1.GruService service.
type GruServiceClient interface {
	// Sessions
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.Session], error)
	LaunchSession(context.Context, *connect.Request[v1.LaunchSessionRequest]) (*connect.Response[v1.LaunchSessionResponse], error)
	KillSession(context.Context, *connect.Request[v1.KillSessionRequest]) (*connect.Response[v1.KillSessionResponse], error)
	SendInput(context.Context, *connect.Request[v1.SendInputRequest]) (*connect.Response[v1.SendInputResponse], error)
	// AI-powered session name suggestion
	SuggestSessionName(context.Context, *connect.Request[v1.SuggestSessionNameRequest]) (*connect.Response[v1.SuggestSessionNameResponse], error)
	// Projects
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.Project], error)
	ListProfiles(context.Context, *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error)
	// Real-time event stream
	SubscribeEvents(context.Context, *connect.Request[v1.SubscribeEventsRequest]) (*connect.ServerStreamForClient[v1.SessionEvent], error)
}

// NewGruServiceClient constructs a client for the gru.v1.GruService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGruServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GruServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	gruServiceMethods := v1.File_gru_v1_gru_proto.Services().ByName("GruService").Methods()
	return &gruServiceClient{
		listSessions: connect.NewClient[v1.ListSessionsRequest, v1.ListSessionsResponse](
			httpClient,
			baseURL+GruServiceListSessionsProcedure,
			connect.WithSchema(gruServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[v1.GetSessionRequest, v1.Session](
			httpClient,
			baseURL+GruServiceGetSessionProcedure,
			connect.WithSchema(gruServiceMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
		launchSession: connect.NewClient[v1.LaunchSessionRequest, v1.LaunchSessionResponse](
			httpClient,
			baseURL+GruServiceLaunchSessionProcedure,
			connect.WithSchema(gruServiceMethods.ByName("LaunchSession")),
			connect.WithClientOptions(opts...),
		),
		killSession: connect.NewClient[v1.KillSessionRequest, v1.KillSessionResponse](
			httpClient,
			baseURL+GruServiceKillSessionProcedure,
			connect.WithSchema(gruServiceMethods.ByName("KillSession")),
			connect.WithClientOptions(opts...),
		),
		sendInput: connect.NewClient[v1.SendInputRequest, v1.SendInputResponse](
			httpClient,
			baseURL+GruServiceSendInputProcedure,
			connect.WithSchema(gruServiceMethods.ByName("SendInput")),
			connect.WithClientOptions(opts...),
		),
		suggestSessionName: connect.NewClient[v1.SuggestSessionNameRequest, v1.SuggestSessionNameResponse](
			httpClient,
			baseURL+GruServiceSuggestSessionNameProcedure,
			connect.WithSchema(gruServiceMethods.ByName("SuggestSessionName")),
			connect.WithClientOptions(opts...),
		),
		listProjects: connect.NewClient[v1.ListProjectsRequest, v1.ListProjectsResponse](
			httpClient,
			baseURL+GruServiceListProjectsProcedure,
			connect.WithSchema(gruServiceMethods.ByName("ListProjects")),
			connect.WithClientOptions(opts...),
		),
		updateProject: connect.NewClient[v1.UpdateProjectRequest, v1.Project](
			httpClient,
			baseURL+GruServiceUpdateProjectProcedure,
			connect.WithSchema(gruServiceMethods.ByName("UpdateProject")),
			connect.WithClientOptions(opts...),
		),
		listProfiles: connect.NewClient[v1.ListProfilesRequest, v1.ListProfilesResponse](
			httpClient,
			baseURL+GruServiceListProfilesProcedure,
			connect.WithSchema(gruServiceMethods.ByName("ListProfiles")),
			connect.WithClientOptions(opts...),
		),
		subscribeEvents: connect.NewClient[v1.SubscribeEventsRequest, v1.SessionEvent](
			httpClient,
			baseURL+GruServiceSubscribeEventsProcedure,
			connect.WithSchema(gruServiceMethods.ByName("SubscribeEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// gruServiceClient implements GruServiceClient.
type gruServiceClient struct {
	listSessions       *connect.Client[v1.ListSessionsRequest, v1.ListSessionsResponse]
	getSession         *connect.Client[v1.GetSessionRequest, v1.Session]
	launchSession      *connect.Client[v1.LaunchSessionRequest, v1.LaunchSessionResponse]
	killSession        *connect.Client[v1.KillSessionRequest, v1.KillSessionResponse]
	sendInput          *connect.Client[v1.SendInputRequest, v1.SendInputResponse]
	suggestSessionName *connect.Client[v1.SuggestSessionNameRequest, v1.SuggestSessionNameResponse]
	listProjects       *connect.Client[v1.ListProjectsRequest, v1.ListProjectsResponse]
	updateProject      *connect.Client[v1.UpdateProjectRequest, v1.Project]
	listProfiles       *connect.Client[v1.ListProfilesRequest, v1.ListProfilesResponse]
	subscribeEvents    *connect.Client[v1.SubscribeEventsRequest, v1.SessionEvent]
}

// ListSessions calls gru.v1.GruService.ListSessions.
func (c *gruServiceClient) ListSessions(ctx context.Context, req *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// GetSession calls gru.v1.GruService.GetSession.
func (c *gruServiceClient) GetSession(ctx context.Context, req *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.Session], error) {
	return c.getSession.CallUnary(ctx, req)
}

// LaunchSession calls gru.v1.GruService.LaunchSession.
func (c *gruServiceClient) LaunchSession(ctx context.Context, req *connect.Request[v1.LaunchSessionRequest]) (*connect.Response[v1.LaunchSessionResponse], error) {
	return c.launchSession.CallUnary(ctx, req)
}

// KillSession calls gru.v1.GruService.KillSession.
func (c *gruServiceClient) KillSession(ctx context.Context, req *connect.Request[v1.KillSessionRequest]) (*connect.Response[v1.KillSessionResponse], error) {
	return c.killSession.CallUnary(ctx, req)
}

// SendInput calls gru.v1.GruService.SendInput.
func (c *gruServiceClient) SendInput(ctx context.Context, req *connect.Request[v1.SendInputRequest]) (*connect.Response[v1.SendInputResponse], error) {
	return c.sendInput.CallUnary(ctx, req)
}

// SuggestSessionName calls gru.v1.GruService.SuggestSessionName.
func (c *gruServiceClient) SuggestSessionName(ctx context.Context, req *connect.Request[v1.SuggestSessionNameRequest]) (*connect.Response[v1.SuggestSessionNameResponse], error) {
	return c.suggestSessionName.CallUnary(ctx, req)
}

// ListProjects calls gru.v1.GruService.ListProjects.
func (c *gruServiceClient) ListProjects(ctx context.Context, req *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// UpdateProject calls gru.v1.GruService.UpdateProject.
func (c *gruServiceClient) UpdateProject(ctx context.Context, req *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.Project], error) {
	return c.updateProject.CallUnary(ctx, req)
}

// ListProfiles calls gru.v1.GruService.ListProfiles.
func (c *gruServiceClient) ListProfiles(ctx context.Context, req *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error) {
	return c.listProfiles.CallUnary(ctx, req)
}

// SubscribeEvents calls gru.v1.GruService.SubscribeEvents.
func (c *gruServiceClient) SubscribeEvents(ctx context.Context, req *connect.Request[v1.SubscribeEventsRequest]) (*connect.ServerStreamForClient[v1.SessionEvent], error) {
	return c.subscribeEvents.CallServerStream(ctx, req)
}

// GruServiceHandler is an implementation of the gru.v1.GruService service.
type GruServiceHandler interface {
	// Sessions
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.Session], error)
	LaunchSession(context.Context, *connect.Request[v1.LaunchSessionRequest]) (*connect.Response[v1.LaunchSessionResponse], error)
	KillSession(context.Context, *connect.Request[v1.KillSessionRequest]) (*connect.Response[v1.KillSessionResponse], error)
	SendInput(context.Context, *connect.Request[v1.SendInputRequest]) (*connect.Response[v1.SendInputResponse], error)
	// AI-powered session name suggestion
	SuggestSessionName(context.Context, *connect.Request[v1.SuggestSessionNameRequest]) (*connect.Response[v1.SuggestSessionNameResponse], error)
	// Projects
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.Project], error)
	ListProfiles(context.Context, *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error)
	// Real-time event stream
	SubscribeEvents(context.Context, *connect.Request[v1.SubscribeEventsRequest], *connect.ServerStream[v1.SessionEvent]) error
}

// NewGruServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGruServiceHandler(svc GruServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gruServiceMethods := v1.File_gru_v1_gru_proto.Services().ByName("GruService").Methods()
	gruServiceListSessionsHandler := connect.NewUnaryHandler(
		GruServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(gruServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	gruServiceGetSessionHandler := connect.NewUnaryHandler(
		GruServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(gruServiceMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	gruServiceLaunchSessionHandler := connect.NewUnaryHandler(
		GruServiceLaunchSessionProcedure,
		svc.LaunchSession,
		connect.WithSchema(gruServiceMethods.ByName("LaunchSession")),
		connect.WithHandlerOptions(opts...),
	)
	gruServiceKillSessionHandler := connect.NewUnaryHandler(
		GruServiceKillSessionProcedure,
		svc.KillSession,
		connect.WithSchema(gruServiceMethods.ByName("KillSession")),
		connect.WithHandlerOptions(opts...),
	)
	gruServiceSendInputHandler := connect.NewUnaryHandler(
		GruServiceSendInputProcedure,
		svc.SendInput,
		connect.WithSchema(gruServiceMethods.ByName("SendInput")),
		connect.WithHandlerOptions(opts...),
	)
	gruServiceSuggestSessionNameHandler := connect.NewUnaryHandler(
		GruServiceSuggestSessionNameProcedure,
		svc.SuggestSessionName,
		connect.WithSchema(gruServiceMethods.ByName("SuggestSessionName")),
		connect.WithHandlerOptions(opts...),
	)
	gruServiceListProjectsHandler := connect.NewUnaryHandler(
		GruServiceListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(gruServiceMethods.ByName("ListProjects")),
		connect.WithHandlerOptions(opts...),
	)
	gruServiceUpdateProjectHandler := connect.NewUnaryHandler(
		GruServiceUpdateProjectProcedure,
		svc.UpdateProject,
		connect.WithSchema(gruServiceMethods.ByName("UpdateProject")),
		connect.WithHandlerOptions(opts...),
	)
	gruServiceListProfilesHandler := connect.NewUnaryHandler(
		GruServiceListProfilesProcedure,
		svc.ListProfiles,
		connect.WithSchema(gruServiceMethods.ByName("ListProfiles")),
		connect.WithHandlerOptions(opts...),
	)
	gruServiceSubscribeEventsHandler := connect.NewServerStreamHandler(
		GruServiceSubscribeEventsProcedure,
		svc.SubscribeEvents,
		connect.WithSchema(gruServiceMethods.ByName("SubscribeEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gru.v1.GruService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GruServiceListSessionsProcedure:
			gruServiceListSessionsHandler.ServeHTTP(w, r)
		case GruServiceGetSessionProcedure:
			gruServiceGetSessionHandler.ServeHTTP(w, r)
		case GruServiceLaunchSessionProcedure:
			gruServiceLaunchSessionHandler.ServeHTTP(w, r)
		case GruServiceKillSessionProcedure:
			gruServiceKillSessionHandler.ServeHTTP(w, r)
		case GruServiceSendInputProcedure:
			gruServiceSendInputHandler.ServeHTTP(w, r)
		case GruServiceSuggestSessionNameProcedure:
			gruServiceSuggestSessionNameHandler.ServeHTTP(w, r)
		case GruServiceListProjectsProcedure:
			gruServiceListProjectsHandler.ServeHTTP(w, r)
		case GruServiceUpdateProjectProcedure:
			gruServiceUpdateProjectHandler.ServeHTTP(w, r)
		case GruServiceListProfilesProcedure:
			gruServiceListProfilesHandler.ServeHTTP(w, r)
		case GruServiceSubscribeEventsProcedure:
			gruServiceSubscribeEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGruServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGruServiceHandler struct{}

func (UnimplementedGruServiceHandler) ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gru.v1.GruService.ListSessions is not implemented"))
}

func (UnimplementedGruServiceHandler) GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.Session], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gru.v1.GruService.GetSession is not implemented"))
}

func (UnimplementedGruServiceHandler) LaunchSession(context.Context, *connect.Request[v1.LaunchSessionRequest]) (*connect.Response[v1.LaunchSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gru.v1.GruService.LaunchSession is not implemented"))
}

func (UnimplementedGruServiceHandler) KillSession(context.Context, *connect.Request[v1.KillSessionRequest]) (*connect.Response[v1.KillSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gru.v1.GruService.KillSession is not implemented"))
}

func (UnimplementedGruServiceHandler) SendInput(context.Context, *connect.Request[v1.SendInputRequest]) (*connect.Response[v1.SendInputResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gru.v1.GruService.SendInput is not implemented"))
}

func (UnimplementedGruServiceHandler) SuggestSessionName(context.Context, *connect.Request[v1.SuggestSessionNameRequest]) (*connect.Response[v1.SuggestSessionNameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gru.v1.GruService.SuggestSessionName is not implemented"))
}

func (UnimplementedGruServiceHandler) ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gru.v1.GruService.ListProjects is not implemented"))
}

func (UnimplementedGruServiceHandler) UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.Project], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gru.v1.GruService.UpdateProject is not implemented"))
}

func (UnimplementedGruServiceHandler) ListProfiles(context.Context, *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gru.v1.GruService.ListProfiles is not implemented"))
}

func (UnimplementedGruServiceHandler) SubscribeEvents(context.Context, *connect.Request[v1.SubscribeEventsRequest], *connect.ServerStream[v1.SessionEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("gru.v1.GruService.SubscribeEvents is not implemented"))
}
