// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/gru/v1/gru.proto

package gruv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED     SessionStatus = 0
	SessionStatus_SESSION_STATUS_STARTING        SessionStatus = 1
	SessionStatus_SESSION_STATUS_RUNNING         SessionStatus = 2
	SessionStatus_SESSION_STATUS_IDLE            SessionStatus = 3
	SessionStatus_SESSION_STATUS_NEEDS_ATTENTION SessionStatus = 4
	SessionStatus_SESSION_STATUS_COMPLETED       SessionStatus = 5
	SessionStatus_SESSION_STATUS_ERRORED         SessionStatus = 6
	SessionStatus_SESSION_STATUS_KILLED          SessionStatus = 7
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_STARTING",
		2: "SESSION_STATUS_RUNNING",
		3: "SESSION_STATUS_IDLE",
		4: "SESSION_STATUS_NEEDS_ATTENTION",
		5: "SESSION_STATUS_COMPLETED",
		6: "SESSION_STATUS_ERRORED",
		7: "SESSION_STATUS_KILLED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED":     0,
		"SESSION_STATUS_STARTING":        1,
		"SESSION_STATUS_RUNNING":         2,
		"SESSION_STATUS_IDLE":            3,
		"SESSION_STATUS_NEEDS_ATTENTION": 4,
		"SESSION_STATUS_COMPLETED":       5,
		"SESSION_STATUS_ERRORED":         6,
		"SESSION_STATUS_KILLED":          7,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gru_v1_gru_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_proto_gru_v1_gru_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_gru_v1_gru_proto_rawDescGZIP(), []int{0}
}

type Session struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Runtime        string                 `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Status         SessionStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=gru.v1.SessionStatus" json:"status,omitempty"`
	Profile        string                 `protobuf:"bytes,5,opt,name=profile,proto3" json:"profile,omitempty"`
	AttentionScore float64                `protobuf:"fixed64,6,opt,name=attention_score,json=attentionScore,proto3" json:"attention_score,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	LastEventAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_event_at,json=lastEventAt,proto3" json:"last_event_at,omitempty"`
	Pid            int32                  `protobuf:"varint,10,opt,name=pid,proto3" json:"pid,omitempty"`
	TmuxSession    string                 `protobuf:"bytes,11,opt,name=tmux_session,json=tmuxSession,proto3" json:"tmux_session,omitempty"`
	TmuxWindow     string                 `protobuf:"bytes,12,opt,name=tmux_window,json=tmuxWindow,proto3" json:"tmux_window,omitempty"`
	Name           string                 `protobuf:"bytes,13,opt,name=name,proto3" json:"name,omitempty"`               // human-readable, e.g. "auth-frontend-bugfix"
	Description    string                 `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"` // what problem is being solved
	Prompt         string                 `protobuf:"bytes,15,opt,name=prompt,proto3" json:"prompt,omitempty"`           // the initial prompt given to the agent
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_gru_v1_gru_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gru_v1_gru_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_gru_v1_gru_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Session) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Session) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *Session) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *Session) GetAttentionScore() float64 {
	if x != nil {
		return x.AttentionScore
	}
	return 0
}

func (x *Session) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Session) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *Session) GetLastEventAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastEventAt
	}
	return nil
}

func (x *Session) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Session) GetTmuxSession() string {
	if x != nil {
		return x.TmuxSession
	}
	return ""
}

func (x *Session) GetTmuxWindow() string {
	if x != nil {
		return x.TmuxWindow
	}
	return ""
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Session) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Runtime       string                 `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_proto_gru_v1_gru_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gru_v1_gru_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_proto_gru_v1_gru_proto_rawDescGZIP(), []int{1}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Project) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Project) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SessionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Runtime       string                 `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_proto_gru_v1_gru_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gru_v1_gru_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_proto_gru_v1_gru_proto_rawDescGZIP(), []int{2}
}

func (x *SessionEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEvent) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SessionEvent) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *SessionEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SessionEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SessionEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Status        SessionStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=gru.v1.SessionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_proto_gru_v1_gru_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gru_v1_gru_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gru_v1_gru_proto_rawDescGZIP(), []int{3}
}

func (x *ListSessionsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListSessionsRequest) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_proto_gru_v1_gru_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gru_v1_gru_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gru_v1_gru_proto_rawDescGZIP(), []int{4}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_proto_gru_v1_gru_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gru_v1_gru_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_gru_v1_gru_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LaunchSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectDir    string                 `protobuf:"bytes,1,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Profile       string                 `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`               // required, human-readable session name
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"` // optional, what problem is being solved
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchSessionRequest) Reset() {
	*x = LaunchSessionRequest{}
	mi := &file_proto_gru_v1_gru_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchSessionRequest) ProtoMessage() {}

func (x *LaunchSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gru_v1_gru_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchSessionRequest.ProtoReflect.Descriptor instead.
func (*LaunchSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_gru_v1_gru_proto_rawDescGZIP(), []int{6}
}

func (x *LaunchSessionRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *LaunchSessionRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *LaunchSessionRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *LaunchSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LaunchSessionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type LaunchSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchSessionResponse) Reset() {
	*x = LaunchSessionResponse{}
	mi := &file_proto_gru_v1_gru_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchSessionResponse) ProtoMessage() {}

func (x *LaunchSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gru_v1_gru_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchSessionResponse.ProtoReflect.Descriptor instead.
func (*LaunchSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_gru_v1_gru_proto_rawDescGZIP(), []int{7}
}

func (x *LaunchSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type KillSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillSessionRequest) Reset() {
	*x = KillSessionRequest{}
	mi := &file_proto_gru_v1_gru_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillSessionRequest) ProtoMessage() {}

func (x *KillSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gru_v1_gru_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillSessionRequest.ProtoReflect.Descriptor instead.
func (*KillSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_gru_v1_gru_proto_rawDescGZIP(), []int{8}
}

func (x *KillSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type KillSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillSessionResponse) Reset() {
	*x = KillSessionResponse{}
	mi := &file_proto_gru_v1_gru_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillSessionResponse) ProtoMessage() {}

func (x *KillSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gru_v1_gru_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillSessionResponse.ProtoReflect.Descriptor instead.
func (*KillSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_gru_v1_gru_proto_rawDescGZIP(), []int{9}
}

func (x *KillSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_proto_gru_v1_gru_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gru_v1_gru_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gru_v1_gru_proto_rawDescGZIP(), []int{10}
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_proto_gru_v1_gru_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gru_v1_gru_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gru_v1_gru_proto_rawDescGZIP(), []int{11}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type SendInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"` // text to send via tmux send-keys
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInputRequest) Reset() {
	*x = SendInputRequest{}
	mi := &file_proto_gru_v1_gru_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInputRequest) ProtoMessage() {}

func (x *SendInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gru_v1_gru_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInputRequest.ProtoReflect.Descriptor instead.
func (*SendInputRequest) Descriptor() ([]byte, []int) {
	return file_proto_gru_v1_gru_proto_rawDescGZIP(), []int{12}
}

func (x *SendInputRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendInputRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInputResponse) Reset() {
	*x = SendInputResponse{}
	mi := &file_proto_gru_v1_gru_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInputResponse) ProtoMessage() {}

func (x *SendInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gru_v1_gru_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInputResponse.ProtoReflect.Descriptor instead.
func (*SendInputResponse) Descriptor() ([]byte, []int) {
	return file_proto_gru_v1_gru_proto_rawDescGZIP(), []int{13}
}

func (x *SendInputResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendInputResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SubscribeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectIds    []string               `protobuf:"bytes,1,rep,name=project_ids,json=projectIds,proto3" json:"project_ids,omitempty"`
	MinAttention  float64                `protobuf:"fixed64,2,opt,name=min_attention,json=minAttention,proto3" json:"min_attention,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_proto_gru_v1_gru_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gru_v1_gru_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gru_v1_gru_proto_rawDescGZIP(), []int{14}
}

func (x *SubscribeEventsRequest) GetProjectIds() []string {
	if x != nil {
		return x.ProjectIds
	}
	return nil
}

func (x *SubscribeEventsRequest) GetMinAttention() float64 {
	if x != nil {
		return x.MinAttention
	}
	return 0
}

var File_proto_gru_v1_gru_proto protoreflect.FileDescriptor

const file_proto_gru_v1_gru_proto_rawDesc = "" +
	"\n" +
	"\x16proto/gru/v1/gru.proto\x12\x06gru.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x04\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.gru.v1.SessionStatusR\x06status\x12\x18\n" +
	"\aprofile\x18\x05 \x01(\tR\aprofile\x12'\n" +
	"\x0fattention_score\x18\x06 \x01(\x01R\x0eattentionScore\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12>\n" +
	"\rlast_event_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vlastEventAt\x12\x10\n" +
	"\x03pid\x18\n" +
	" \x01(\x05R\x03pid\x12!\n" +
	"\ftmux_session\x18\v \x01(\tR\vtmuxSession\x12\x1f\n" +
	"\vtmux_window\x18\f \x01(\tR\n" +
	"tmuxWindow\x12\x12\n" +
	"\x04name\x18\r \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x0e \x01(\tR\vdescription\x12\x16\n" +
	"\x06prompt\x18\x0f \x01(\tR\x06prompt\"\x96\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x18\n" +
	"\aruntime\x18\x04 \x01(\tR\aruntime\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xde\x01\n" +
	"\fSessionEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x18\n" +
	"\aruntime\x18\x04 \x01(\tR\aruntime\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\"c\n" +
	"\x13ListSessionsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.gru.v1.SessionStatusR\x06status\"C\n" +
	"\x14ListSessionsResponse\x12+\n" +
	"\bsessions\x18\x01 \x03(\v2\x0f.gru.v1.SessionR\bsessions\"#\n" +
	"\x11GetSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9f\x01\n" +
	"\x14LaunchSessionRequest\x12\x1f\n" +
	"\vproject_dir\x18\x01 \x01(\tR\n" +
	"projectDir\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x18\n" +
	"\aprofile\x18\x03 \x01(\tR\aprofile\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"B\n" +
	"\x15LaunchSessionResponse\x12)\n" +
	"\asession\x18\x01 \x01(\v2\x0f.gru.v1.SessionR\asession\"$\n" +
	"\x12KillSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13KillSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x15\n" +
	"\x13ListProjectsRequest\"C\n" +
	"\x14ListProjectsResponse\x12+\n" +
	"\bprojects\x18\x01 \x03(\v2\x0f.gru.v1.ProjectR\bprojects\"E\n" +
	"\x10SendInputRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"R\n" +
	"\x11SendInputResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"^\n" +
	"\x16SubscribeEventsRequest\x12\x1f\n" +
	"\vproject_ids\x18\x01 \x03(\tR\n" +
	"projectIds\x12#\n" +
	"\rmin_attention\x18\x02 \x01(\x01R\fminAttention*\xfa\x01\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SESSION_STATUS_STARTING\x10\x01\x12\x1a\n" +
	"\x16SESSION_STATUS_RUNNING\x10\x02\x12\x17\n" +
	"\x13SESSION_STATUS_IDLE\x10\x03\x12\"\n" +
	"\x1eSESSION_STATUS_NEEDS_ATTENTION\x10\x04\x12\x1c\n" +
	"\x18SESSION_STATUS_COMPLETED\x10\x05\x12\x1a\n" +
	"\x16SESSION_STATUS_ERRORED\x10\x06\x12\x19\n" +
	"\x15SESSION_STATUS_KILLED\x10\a2\xff\x03\n" +
	"\n" +
	"GruService\x12I\n" +
	"\fListSessions\x12\x1b.gru.v1.ListSessionsRequest\x1a\x1c.gru.v1.ListSessionsResponse\x128\n" +
	"\n" +
	"GetSession\x12\x19.gru.v1.GetSessionRequest\x1a\x0f.gru.v1.Session\x12L\n" +
	"\rLaunchSession\x12\x1c.gru.v1.LaunchSessionRequest\x1a\x1d.gru.v1.LaunchSessionResponse\x12F\n" +
	"\vKillSession\x12\x1a.gru.v1.KillSessionRequest\x1a\x1b.gru.v1.KillSessionResponse\x12@\n" +
	"\tSendInput\x12\x18.gru.v1.SendInputRequest\x1a\x19.gru.v1.SendInputResponse\x12I\n" +
	"\fListProjects\x12\x1b.gru.v1.ListProjectsRequest\x1a\x1c.gru.v1.ListProjectsResponse\x12I\n" +
	"\x0fSubscribeEvents\x12\x1e.gru.v1.SubscribeEventsRequest\x1a\x14.gru.v1.SessionEvent0\x01B\x7f\n" +
	"\n" +
	"com.gru.v1B\bGruProtoP\x01Z.github.com/dakshjotwani/gru/proto/gru/v1;gruv1\xa2\x02\x03GXX\xaa\x02\x06Gru.V1\xca\x02\x06Gru\\V1\xe2\x02\x12Gru\\V1\\GPBMetadata\xea\x02\aGru::V1b\x06proto3"

var (
	file_proto_gru_v1_gru_proto_rawDescOnce sync.Once
	file_proto_gru_v1_gru_proto_rawDescData []byte
)

func file_proto_gru_v1_gru_proto_rawDescGZIP() []byte {
	file_proto_gru_v1_gru_proto_rawDescOnce.Do(func() {
		file_proto_gru_v1_gru_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gru_v1_gru_proto_rawDesc), len(file_proto_gru_v1_gru_proto_rawDesc)))
	})
	return file_proto_gru_v1_gru_proto_rawDescData
}

var file_proto_gru_v1_gru_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_gru_v1_gru_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_gru_v1_gru_proto_goTypes = []any{
	(SessionStatus)(0),             // 0: gru.v1.SessionStatus
	(*Session)(nil),                // 1: gru.v1.Session
	(*Project)(nil),                // 2: gru.v1.Project
	(*SessionEvent)(nil),           // 3: gru.v1.SessionEvent
	(*ListSessionsRequest)(nil),    // 4: gru.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),   // 5: gru.v1.ListSessionsResponse
	(*GetSessionRequest)(nil),      // 6: gru.v1.GetSessionRequest
	(*LaunchSessionRequest)(nil),   // 7: gru.v1.LaunchSessionRequest
	(*LaunchSessionResponse)(nil),  // 8: gru.v1.LaunchSessionResponse
	(*KillSessionRequest)(nil),     // 9: gru.v1.KillSessionRequest
	(*KillSessionResponse)(nil),    // 10: gru.v1.KillSessionResponse
	(*ListProjectsRequest)(nil),    // 11: gru.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),   // 12: gru.v1.ListProjectsResponse
	(*SendInputRequest)(nil),       // 13: gru.v1.SendInputRequest
	(*SendInputResponse)(nil),      // 14: gru.v1.SendInputResponse
	(*SubscribeEventsRequest)(nil), // 15: gru.v1.SubscribeEventsRequest
	(*timestamppb.Timestamp)(nil),  // 16: google.protobuf.Timestamp
}
var file_proto_gru_v1_gru_proto_depIdxs = []int32{
	0,  // 0: gru.v1.Session.status:type_name -> gru.v1.SessionStatus
	16, // 1: gru.v1.Session.started_at:type_name -> google.protobuf.Timestamp
	16, // 2: gru.v1.Session.ended_at:type_name -> google.protobuf.Timestamp
	16, // 3: gru.v1.Session.last_event_at:type_name -> google.protobuf.Timestamp
	16, // 4: gru.v1.Project.created_at:type_name -> google.protobuf.Timestamp
	16, // 5: gru.v1.SessionEvent.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 6: gru.v1.ListSessionsRequest.status:type_name -> gru.v1.SessionStatus
	1,  // 7: gru.v1.ListSessionsResponse.sessions:type_name -> gru.v1.Session
	1,  // 8: gru.v1.LaunchSessionResponse.session:type_name -> gru.v1.Session
	2,  // 9: gru.v1.ListProjectsResponse.projects:type_name -> gru.v1.Project
	4,  // 10: gru.v1.GruService.ListSessions:input_type -> gru.v1.ListSessionsRequest
	6,  // 11: gru.v1.GruService.GetSession:input_type -> gru.v1.GetSessionRequest
	7,  // 12: gru.v1.GruService.LaunchSession:input_type -> gru.v1.LaunchSessionRequest
	9,  // 13: gru.v1.GruService.KillSession:input_type -> gru.v1.KillSessionRequest
	13, // 14: gru.v1.GruService.SendInput:input_type -> gru.v1.SendInputRequest
	11, // 15: gru.v1.GruService.ListProjects:input_type -> gru.v1.ListProjectsRequest
	15, // 16: gru.v1.GruService.SubscribeEvents:input_type -> gru.v1.SubscribeEventsRequest
	5,  // 17: gru.v1.GruService.ListSessions:output_type -> gru.v1.ListSessionsResponse
	1,  // 18: gru.v1.GruService.GetSession:output_type -> gru.v1.Session
	8,  // 19: gru.v1.GruService.LaunchSession:output_type -> gru.v1.LaunchSessionResponse
	10, // 20: gru.v1.GruService.KillSession:output_type -> gru.v1.KillSessionResponse
	14, // 21: gru.v1.GruService.SendInput:output_type -> gru.v1.SendInputResponse
	12, // 22: gru.v1.GruService.ListProjects:output_type -> gru.v1.ListProjectsResponse
	3,  // 23: gru.v1.GruService.SubscribeEvents:output_type -> gru.v1.SessionEvent
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_gru_v1_gru_proto_init() }
func file_proto_gru_v1_gru_proto_init() {
	if File_proto_gru_v1_gru_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gru_v1_gru_proto_rawDesc), len(file_proto_gru_v1_gru_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gru_v1_gru_proto_goTypes,
		DependencyIndexes: file_proto_gru_v1_gru_proto_depIdxs,
		EnumInfos:         file_proto_gru_v1_gru_proto_enumTypes,
		MessageInfos:      file_proto_gru_v1_gru_proto_msgTypes,
	}.Build()
	File_proto_gru_v1_gru_proto = out.File
	file_proto_gru_v1_gru_proto_goTypes = nil
	file_proto_gru_v1_gru_proto_depIdxs = nil
}
