// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gru/v1/gru.proto

package gruv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED     SessionStatus = 0
	SessionStatus_SESSION_STATUS_STARTING        SessionStatus = 1
	SessionStatus_SESSION_STATUS_RUNNING         SessionStatus = 2
	SessionStatus_SESSION_STATUS_IDLE            SessionStatus = 3
	SessionStatus_SESSION_STATUS_NEEDS_ATTENTION SessionStatus = 4
	SessionStatus_SESSION_STATUS_COMPLETED       SessionStatus = 5
	SessionStatus_SESSION_STATUS_ERRORED         SessionStatus = 6
	SessionStatus_SESSION_STATUS_KILLED          SessionStatus = 7
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_STARTING",
		2: "SESSION_STATUS_RUNNING",
		3: "SESSION_STATUS_IDLE",
		4: "SESSION_STATUS_NEEDS_ATTENTION",
		5: "SESSION_STATUS_COMPLETED",
		6: "SESSION_STATUS_ERRORED",
		7: "SESSION_STATUS_KILLED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED":     0,
		"SESSION_STATUS_STARTING":        1,
		"SESSION_STATUS_RUNNING":         2,
		"SESSION_STATUS_IDLE":            3,
		"SESSION_STATUS_NEEDS_ATTENTION": 4,
		"SESSION_STATUS_COMPLETED":       5,
		"SESSION_STATUS_ERRORED":         6,
		"SESSION_STATUS_KILLED":          7,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gru_v1_gru_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_gru_v1_gru_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{0}
}

type Session struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Runtime        string                 `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Status         SessionStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=gru.v1.SessionStatus" json:"status,omitempty"`
	Profile        string                 `protobuf:"bytes,5,opt,name=profile,proto3" json:"profile,omitempty"`
	AttentionScore float64                `protobuf:"fixed64,6,opt,name=attention_score,json=attentionScore,proto3" json:"attention_score,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	LastEventAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_event_at,json=lastEventAt,proto3" json:"last_event_at,omitempty"`
	Pid            int32                  `protobuf:"varint,10,opt,name=pid,proto3" json:"pid,omitempty"`
	TmuxSession    string                 `protobuf:"bytes,11,opt,name=tmux_session,json=tmuxSession,proto3" json:"tmux_session,omitempty"`
	TmuxWindow     string                 `protobuf:"bytes,12,opt,name=tmux_window,json=tmuxWindow,proto3" json:"tmux_window,omitempty"`
	Name           string                 `protobuf:"bytes,13,opt,name=name,proto3" json:"name,omitempty"`               // human-readable, e.g. "auth-frontend-bugfix"
	Description    string                 `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"` // what problem is being solved
	Prompt         string                 `protobuf:"bytes,15,opt,name=prompt,proto3" json:"prompt,omitempty"`           // the initial prompt given to the agent
	Role           string                 `protobuf:"bytes,16,opt,name=role,proto3" json:"role,omitempty"`               // "" for normal sessions; "journal" marks the server-managed singleton
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_gru_v1_gru_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Session) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Session) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *Session) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *Session) GetAttentionScore() float64 {
	if x != nil {
		return x.AttentionScore
	}
	return 0
}

func (x *Session) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Session) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *Session) GetLastEventAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastEventAt
	}
	return nil
}

func (x *Session) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Session) GetTmuxSession() string {
	if x != nil {
		return x.TmuxSession
	}
	return ""
}

func (x *Session) GetTmuxWindow() string {
	if x != nil {
		return x.TmuxWindow
	}
	return ""
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Session) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Session) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// Project is a reference to an env spec on disk. Project.id is the absolute
// path to the spec.yaml file; Project.name is the directory basename (used
// for display). Workdirs, adapter config, and everything else about how a
// session runs lives in the spec file itself — Gru stores only the pointer.
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // absolute path to spec.yaml (also the PK in SQLite)
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`       // display name (usually the directory basename)
	Adapter       string                 `protobuf:"bytes,3,opt,name=adapter,proto3" json:"adapter,omitempty"` // cached from the spec for listing without a disk read
	Runtime       string                 `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"` // agent runtime, e.g. "claude-code"
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_gru_v1_gru_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{1}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetAdapter() string {
	if x != nil {
		return x.Adapter
	}
	return ""
}

func (x *Project) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Project) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SessionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Runtime       string                 `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_gru_v1_gru_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{2}
}

func (x *SessionEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEvent) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SessionEvent) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *SessionEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SessionEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SessionEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Status        SessionStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=gru.v1.SessionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_gru_v1_gru_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{3}
}

func (x *ListSessionsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListSessionsRequest) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_gru_v1_gru_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{4}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_gru_v1_gru_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// LaunchSessionRequest picks an env spec and launches an agent in it. The
// spec declares everything about where the session runs — workdirs,
// adapter, source isolation, mounts — so the launch payload is minimal.
type LaunchSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Either an absolute path to a spec.yaml file, or a project
	// name that resolves to ~/.gru/projects/<name>/spec.yaml.
	EnvSpec       string `protobuf:"bytes,1,opt,name=env_spec,json=envSpec,proto3" json:"env_spec,omitempty"`
	Prompt        string `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`           // required
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`               // required, human-readable session label
	Description   string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"` // optional, what problem the session is solving
	Profile       string `protobuf:"bytes,5,opt,name=profile,proto3" json:"profile,omitempty"`         // optional agent profile name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchSessionRequest) Reset() {
	*x = LaunchSessionRequest{}
	mi := &file_gru_v1_gru_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchSessionRequest) ProtoMessage() {}

func (x *LaunchSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchSessionRequest.ProtoReflect.Descriptor instead.
func (*LaunchSessionRequest) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{6}
}

func (x *LaunchSessionRequest) GetEnvSpec() string {
	if x != nil {
		return x.EnvSpec
	}
	return ""
}

func (x *LaunchSessionRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *LaunchSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LaunchSessionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LaunchSessionRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type LaunchSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchSessionResponse) Reset() {
	*x = LaunchSessionResponse{}
	mi := &file_gru_v1_gru_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchSessionResponse) ProtoMessage() {}

func (x *LaunchSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchSessionResponse.ProtoReflect.Descriptor instead.
func (*LaunchSessionResponse) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{7}
}

func (x *LaunchSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type KillSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillSessionRequest) Reset() {
	*x = KillSessionRequest{}
	mi := &file_gru_v1_gru_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillSessionRequest) ProtoMessage() {}

func (x *KillSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillSessionRequest.ProtoReflect.Descriptor instead.
func (*KillSessionRequest) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{8}
}

func (x *KillSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type KillSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillSessionResponse) Reset() {
	*x = KillSessionResponse{}
	mi := &file_gru_v1_gru_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillSessionResponse) ProtoMessage() {}

func (x *KillSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillSessionResponse.ProtoReflect.Descriptor instead.
func (*KillSessionResponse) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{9}
}

func (x *KillSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// DeleteSession removes a terminal (completed/errored/killed) session row
// and its events. Live sessions must be KillSessioned first — the server
// rejects the request if the session is still active.
type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_gru_v1_gru_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_gru_v1_gru_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// PruneSessions removes every terminal session row at once. Assistant-role
// sessions are never deleted (server-managed). Intended for UI "clear
// completed" actions.
type PruneSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneSessionsRequest) Reset() {
	*x = PruneSessionsRequest{}
	mi := &file_gru_v1_gru_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneSessionsRequest) ProtoMessage() {}

func (x *PruneSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneSessionsRequest.ProtoReflect.Descriptor instead.
func (*PruneSessionsRequest) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{12}
}

type PruneSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneSessionsResponse) Reset() {
	*x = PruneSessionsResponse{}
	mi := &file_gru_v1_gru_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneSessionsResponse) ProtoMessage() {}

func (x *PruneSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneSessionsResponse.ProtoReflect.Descriptor instead.
func (*PruneSessionsResponse) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{13}
}

func (x *PruneSessionsResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_gru_v1_gru_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{14}
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_gru_v1_gru_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{15}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

// UpdateProjectRequest lets the UI rename a project (rename the directory
// under ~/.gru/projects/). Workdirs / adapter config are edited by hand in
// the spec file, not through the API.
type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                          // absolute spec path
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"` // optional rename; empty = no change
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_gru_v1_gru_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProjectRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type AgentProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentProfile) Reset() {
	*x = AgentProfile{}
	mi := &file_gru_v1_gru_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentProfile) ProtoMessage() {}

func (x *AgentProfile) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentProfile.ProtoReflect.Descriptor instead.
func (*AgentProfile) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{17}
}

func (x *AgentProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentProfile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentProfile) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// ListProfilesRequest asks for agent profiles associated with a project.
// project_id is the spec path so the server can look at the spec's workdirs
// for local profile files (e.g. .gru/profiles.yaml inside workdirs[0]).
type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_gru_v1_gru_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{18}
}

func (x *ListProfilesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*AgentProfile        `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_gru_v1_gru_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{19}
}

func (x *ListProfilesResponse) GetProfiles() []*AgentProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type SendInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"` // text to send via tmux send-keys
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInputRequest) Reset() {
	*x = SendInputRequest{}
	mi := &file_gru_v1_gru_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInputRequest) ProtoMessage() {}

func (x *SendInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInputRequest.ProtoReflect.Descriptor instead.
func (*SendInputRequest) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{20}
}

func (x *SendInputRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendInputRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInputResponse) Reset() {
	*x = SendInputResponse{}
	mi := &file_gru_v1_gru_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInputResponse) ProtoMessage() {}

func (x *SendInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInputResponse.ProtoReflect.Descriptor instead.
func (*SendInputResponse) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{21}
}

func (x *SendInputResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendInputResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SubscribeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectIds    []string               `protobuf:"bytes,1,rep,name=project_ids,json=projectIds,proto3" json:"project_ids,omitempty"`
	MinAttention  float64                `protobuf:"fixed64,2,opt,name=min_attention,json=minAttention,proto3" json:"min_attention,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_gru_v1_gru_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{22}
}

func (x *SubscribeEventsRequest) GetProjectIds() []string {
	if x != nil {
		return x.ProjectIds
	}
	return nil
}

func (x *SubscribeEventsRequest) GetMinAttention() float64 {
	if x != nil {
		return x.MinAttention
	}
	return 0
}

type SuggestSessionNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // absolute spec path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestSessionNameRequest) Reset() {
	*x = SuggestSessionNameRequest{}
	mi := &file_gru_v1_gru_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestSessionNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestSessionNameRequest) ProtoMessage() {}

func (x *SuggestSessionNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestSessionNameRequest.ProtoReflect.Descriptor instead.
func (*SuggestSessionNameRequest) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{23}
}

func (x *SuggestSessionNameRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *SuggestSessionNameRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type SuggestSessionNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestSessionNameResponse) Reset() {
	*x = SuggestSessionNameResponse{}
	mi := &file_gru_v1_gru_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestSessionNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestSessionNameResponse) ProtoMessage() {}

func (x *SuggestSessionNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestSessionNameResponse.ProtoReflect.Descriptor instead.
func (*SuggestSessionNameResponse) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{24}
}

func (x *SuggestSessionNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SuggestSessionNameResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Artifact: a byte payload (PDF, Markdown, etc.) surfaced by an agent.
// `url` is the full server-relative path including the capability token
// (e.g. /artifacts/<base64url-token>) — anyone holding that URL can fetch
// the bytes, anyone who doesn't cannot.
type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_gru_v1_gru_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{25}
}

func (x *Artifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artifact) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Artifact) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Artifact) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Artifact) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Artifact) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Artifact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListArtifactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsRequest) Reset() {
	*x = ListArtifactsRequest{}
	mi := &file_gru_v1_gru_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsRequest) ProtoMessage() {}

func (x *ListArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsRequest.ProtoReflect.Descriptor instead.
func (*ListArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{26}
}

func (x *ListArtifactsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ListArtifactsResponse exposes count + bytes_used so an agent can
// pre-check whether a planned upload will hit the per-session caps. The
// 409 cap-exceeded response from POST /artifacts returns the same fields.
type ListArtifactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*Artifact            `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	BytesUsed     int64                  `protobuf:"varint,3,opt,name=bytes_used,json=bytesUsed,proto3" json:"bytes_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsResponse) Reset() {
	*x = ListArtifactsResponse{}
	mi := &file_gru_v1_gru_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsResponse) ProtoMessage() {}

func (x *ListArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsResponse.ProtoReflect.Descriptor instead.
func (*ListArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{27}
}

func (x *ListArtifactsResponse) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ListArtifactsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListArtifactsResponse) GetBytesUsed() int64 {
	if x != nil {
		return x.BytesUsed
	}
	return 0
}

type DeleteArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArtifactRequest) Reset() {
	*x = DeleteArtifactRequest{}
	mi := &file_gru_v1_gru_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtifactRequest) ProtoMessage() {}

func (x *DeleteArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtifactRequest.ProtoReflect.Descriptor instead.
func (*DeleteArtifactRequest) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteArtifactRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArtifactResponse) Reset() {
	*x = DeleteArtifactResponse{}
	mi := &file_gru_v1_gru_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtifactResponse) ProtoMessage() {}

func (x *DeleteArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtifactResponse.ProtoReflect.Descriptor instead.
func (*DeleteArtifactResponse) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteArtifactResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// SessionLink: an external URL pointer attached to a session. Icons are
// derived client-side from the URL hostname — the server does not store one.
type SessionLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionLink) Reset() {
	*x = SessionLink{}
	mi := &file_gru_v1_gru_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionLink) ProtoMessage() {}

func (x *SessionLink) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionLink.ProtoReflect.Descriptor instead.
func (*SessionLink) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{30}
}

func (x *SessionLink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionLink) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionLink) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SessionLink) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SessionLink) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AddSessionLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSessionLinkRequest) Reset() {
	*x = AddSessionLinkRequest{}
	mi := &file_gru_v1_gru_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSessionLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSessionLinkRequest) ProtoMessage() {}

func (x *AddSessionLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSessionLinkRequest.ProtoReflect.Descriptor instead.
func (*AddSessionLinkRequest) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{31}
}

func (x *AddSessionLinkRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddSessionLinkRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddSessionLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ListSessionLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionLinksRequest) Reset() {
	*x = ListSessionLinksRequest{}
	mi := &file_gru_v1_gru_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionLinksRequest) ProtoMessage() {}

func (x *ListSessionLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionLinksRequest.ProtoReflect.Descriptor instead.
func (*ListSessionLinksRequest) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{32}
}

func (x *ListSessionLinksRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListSessionLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*SessionLink         `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionLinksResponse) Reset() {
	*x = ListSessionLinksResponse{}
	mi := &file_gru_v1_gru_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionLinksResponse) ProtoMessage() {}

func (x *ListSessionLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionLinksResponse.ProtoReflect.Descriptor instead.
func (*ListSessionLinksResponse) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{33}
}

func (x *ListSessionLinksResponse) GetLinks() []*SessionLink {
	if x != nil {
		return x.Links
	}
	return nil
}

type DeleteSessionLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionLinkRequest) Reset() {
	*x = DeleteSessionLinkRequest{}
	mi := &file_gru_v1_gru_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionLinkRequest) ProtoMessage() {}

func (x *DeleteSessionLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionLinkRequest) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{34}
}

func (x *DeleteSessionLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSessionLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionLinkResponse) Reset() {
	*x = DeleteSessionLinkResponse{}
	mi := &file_gru_v1_gru_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionLinkResponse) ProtoMessage() {}

func (x *DeleteSessionLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gru_v1_gru_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionLinkResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionLinkResponse) Descriptor() ([]byte, []int) {
	return file_gru_v1_gru_proto_rawDescGZIP(), []int{35}
}

func (x *DeleteSessionLinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_gru_v1_gru_proto protoreflect.FileDescriptor

const file_gru_v1_gru_proto_rawDesc = "" +
	"\n" +
	"\x10gru/v1/gru.proto\x12\x06gru.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x04\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.gru.v1.SessionStatusR\x06status\x12\x18\n" +
	"\aprofile\x18\x05 \x01(\tR\aprofile\x12'\n" +
	"\x0fattention_score\x18\x06 \x01(\x01R\x0eattentionScore\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12>\n" +
	"\rlast_event_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vlastEventAt\x12\x10\n" +
	"\x03pid\x18\n" +
	" \x01(\x05R\x03pid\x12!\n" +
	"\ftmux_session\x18\v \x01(\tR\vtmuxSession\x12\x1f\n" +
	"\vtmux_window\x18\f \x01(\tR\n" +
	"tmuxWindow\x12\x12\n" +
	"\x04name\x18\r \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x0e \x01(\tR\vdescription\x12\x16\n" +
	"\x06prompt\x18\x0f \x01(\tR\x06prompt\x12\x12\n" +
	"\x04role\x18\x10 \x01(\tR\x04role\"\x9c\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aadapter\x18\x03 \x01(\tR\aadapter\x12\x18\n" +
	"\aruntime\x18\x04 \x01(\tR\aruntime\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xde\x01\n" +
	"\fSessionEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x18\n" +
	"\aruntime\x18\x04 \x01(\tR\aruntime\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\"c\n" +
	"\x13ListSessionsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.gru.v1.SessionStatusR\x06status\"C\n" +
	"\x14ListSessionsResponse\x12+\n" +
	"\bsessions\x18\x01 \x03(\v2\x0f.gru.v1.SessionR\bsessions\"#\n" +
	"\x11GetSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x99\x01\n" +
	"\x14LaunchSessionRequest\x12\x19\n" +
	"\benv_spec\x18\x01 \x01(\tR\aenvSpec\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aprofile\x18\x05 \x01(\tR\aprofile\"B\n" +
	"\x15LaunchSessionResponse\x12)\n" +
	"\asession\x18\x01 \x01(\v2\x0f.gru.v1.SessionR\asession\"$\n" +
	"\x12KillSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13KillSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"&\n" +
	"\x14DeleteSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x16\n" +
	"\x14PruneSessionsRequest\"<\n" +
	"\x15PruneSessionsResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\"\x15\n" +
	"\x13ListProjectsRequest\"C\n" +
	"\x14ListProjectsResponse\x12+\n" +
	"\bprojects\x18\x01 \x03(\v2\x0f.gru.v1.ProjectR\bprojects\"A\n" +
	"\x14UpdateProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"Z\n" +
	"\fAgentProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"4\n" +
	"\x13ListProfilesRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"H\n" +
	"\x14ListProfilesResponse\x120\n" +
	"\bprofiles\x18\x01 \x03(\v2\x14.gru.v1.AgentProfileR\bprofiles\"E\n" +
	"\x10SendInputRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"R\n" +
	"\x11SendInputResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"^\n" +
	"\x16SubscribeEventsRequest\x12\x1f\n" +
	"\vproject_ids\x18\x01 \x03(\tR\n" +
	"projectIds\x12#\n" +
	"\rmin_attention\x18\x02 \x01(\x01R\fminAttention\"R\n" +
	"\x19SuggestSessionNameRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"R\n" +
	"\x1aSuggestSessionNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xd8\x01\n" +
	"\bArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"5\n" +
	"\x14ListArtifactsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"|\n" +
	"\x15ListArtifactsResponse\x12.\n" +
	"\tartifacts\x18\x01 \x03(\v2\x10.gru.v1.ArtifactR\tartifacts\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1d\n" +
	"\n" +
	"bytes_used\x18\x03 \x01(\x03R\tbytesUsed\"'\n" +
	"\x15DeleteArtifactRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteArtifactResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9f\x01\n" +
	"\vSessionLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"^\n" +
	"\x15AddSessionLinkRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"8\n" +
	"\x17ListSessionLinksRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"E\n" +
	"\x18ListSessionLinksResponse\x12)\n" +
	"\x05links\x18\x01 \x03(\v2\x13.gru.v1.SessionLinkR\x05links\"*\n" +
	"\x18DeleteSessionLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x19DeleteSessionLinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\xfa\x01\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SESSION_STATUS_STARTING\x10\x01\x12\x1a\n" +
	"\x16SESSION_STATUS_RUNNING\x10\x02\x12\x17\n" +
	"\x13SESSION_STATUS_IDLE\x10\x03\x12\"\n" +
	"\x1eSESSION_STATUS_NEEDS_ATTENTION\x10\x04\x12\x1c\n" +
	"\x18SESSION_STATUS_COMPLETED\x10\x05\x12\x1a\n" +
	"\x16SESSION_STATUS_ERRORED\x10\x06\x12\x19\n" +
	"\x15SESSION_STATUS_KILLED\x10\a2\x99\n" +
	"\n" +
	"\n" +
	"GruService\x12I\n" +
	"\fListSessions\x12\x1b.gru.v1.ListSessionsRequest\x1a\x1c.gru.v1.ListSessionsResponse\x128\n" +
	"\n" +
	"GetSession\x12\x19.gru.v1.GetSessionRequest\x1a\x0f.gru.v1.Session\x12L\n" +
	"\rLaunchSession\x12\x1c.gru.v1.LaunchSessionRequest\x1a\x1d.gru.v1.LaunchSessionResponse\x12F\n" +
	"\vKillSession\x12\x1a.gru.v1.KillSessionRequest\x1a\x1b.gru.v1.KillSessionResponse\x12L\n" +
	"\rDeleteSession\x12\x1c.gru.v1.DeleteSessionRequest\x1a\x1d.gru.v1.DeleteSessionResponse\x12L\n" +
	"\rPruneSessions\x12\x1c.gru.v1.PruneSessionsRequest\x1a\x1d.gru.v1.PruneSessionsResponse\x12@\n" +
	"\tSendInput\x12\x18.gru.v1.SendInputRequest\x1a\x19.gru.v1.SendInputResponse\x12[\n" +
	"\x12SuggestSessionName\x12!.gru.v1.SuggestSessionNameRequest\x1a\".gru.v1.SuggestSessionNameResponse\x12I\n" +
	"\fListProjects\x12\x1b.gru.v1.ListProjectsRequest\x1a\x1c.gru.v1.ListProjectsResponse\x12>\n" +
	"\rUpdateProject\x12\x1c.gru.v1.UpdateProjectRequest\x1a\x0f.gru.v1.Project\x12I\n" +
	"\fListProfiles\x12\x1b.gru.v1.ListProfilesRequest\x1a\x1c.gru.v1.ListProfilesResponse\x12L\n" +
	"\rListArtifacts\x12\x1c.gru.v1.ListArtifactsRequest\x1a\x1d.gru.v1.ListArtifactsResponse\x12O\n" +
	"\x0eDeleteArtifact\x12\x1d.gru.v1.DeleteArtifactRequest\x1a\x1e.gru.v1.DeleteArtifactResponse\x12D\n" +
	"\x0eAddSessionLink\x12\x1d.gru.v1.AddSessionLinkRequest\x1a\x13.gru.v1.SessionLink\x12U\n" +
	"\x10ListSessionLinks\x12\x1f.gru.v1.ListSessionLinksRequest\x1a .gru.v1.ListSessionLinksResponse\x12X\n" +
	"\x11DeleteSessionLink\x12 .gru.v1.DeleteSessionLinkRequest\x1a!.gru.v1.DeleteSessionLinkResponse\x12I\n" +
	"\x0fSubscribeEvents\x12\x1e.gru.v1.SubscribeEventsRequest\x1a\x14.gru.v1.SessionEvent0\x01B\x7f\n" +
	"\n" +
	"com.gru.v1B\bGruProtoP\x01Z.github.com/dakshjotwani/gru/proto/gru/v1;gruv1\xa2\x02\x03GXX\xaa\x02\x06Gru.V1\xca\x02\x06Gru\\V1\xe2\x02\x12Gru\\V1\\GPBMetadata\xea\x02\aGru::V1b\x06proto3"

var (
	file_gru_v1_gru_proto_rawDescOnce sync.Once
	file_gru_v1_gru_proto_rawDescData []byte
)

func file_gru_v1_gru_proto_rawDescGZIP() []byte {
	file_gru_v1_gru_proto_rawDescOnce.Do(func() {
		file_gru_v1_gru_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gru_v1_gru_proto_rawDesc), len(file_gru_v1_gru_proto_rawDesc)))
	})
	return file_gru_v1_gru_proto_rawDescData
}

var file_gru_v1_gru_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gru_v1_gru_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_gru_v1_gru_proto_goTypes = []any{
	(SessionStatus)(0),                 // 0: gru.v1.SessionStatus
	(*Session)(nil),                    // 1: gru.v1.Session
	(*Project)(nil),                    // 2: gru.v1.Project
	(*SessionEvent)(nil),               // 3: gru.v1.SessionEvent
	(*ListSessionsRequest)(nil),        // 4: gru.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),       // 5: gru.v1.ListSessionsResponse
	(*GetSessionRequest)(nil),          // 6: gru.v1.GetSessionRequest
	(*LaunchSessionRequest)(nil),       // 7: gru.v1.LaunchSessionRequest
	(*LaunchSessionResponse)(nil),      // 8: gru.v1.LaunchSessionResponse
	(*KillSessionRequest)(nil),         // 9: gru.v1.KillSessionRequest
	(*KillSessionResponse)(nil),        // 10: gru.v1.KillSessionResponse
	(*DeleteSessionRequest)(nil),       // 11: gru.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil),      // 12: gru.v1.DeleteSessionResponse
	(*PruneSessionsRequest)(nil),       // 13: gru.v1.PruneSessionsRequest
	(*PruneSessionsResponse)(nil),      // 14: gru.v1.PruneSessionsResponse
	(*ListProjectsRequest)(nil),        // 15: gru.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),       // 16: gru.v1.ListProjectsResponse
	(*UpdateProjectRequest)(nil),       // 17: gru.v1.UpdateProjectRequest
	(*AgentProfile)(nil),               // 18: gru.v1.AgentProfile
	(*ListProfilesRequest)(nil),        // 19: gru.v1.ListProfilesRequest
	(*ListProfilesResponse)(nil),       // 20: gru.v1.ListProfilesResponse
	(*SendInputRequest)(nil),           // 21: gru.v1.SendInputRequest
	(*SendInputResponse)(nil),          // 22: gru.v1.SendInputResponse
	(*SubscribeEventsRequest)(nil),     // 23: gru.v1.SubscribeEventsRequest
	(*SuggestSessionNameRequest)(nil),  // 24: gru.v1.SuggestSessionNameRequest
	(*SuggestSessionNameResponse)(nil), // 25: gru.v1.SuggestSessionNameResponse
	(*Artifact)(nil),                   // 26: gru.v1.Artifact
	(*ListArtifactsRequest)(nil),       // 27: gru.v1.ListArtifactsRequest
	(*ListArtifactsResponse)(nil),      // 28: gru.v1.ListArtifactsResponse
	(*DeleteArtifactRequest)(nil),      // 29: gru.v1.DeleteArtifactRequest
	(*DeleteArtifactResponse)(nil),     // 30: gru.v1.DeleteArtifactResponse
	(*SessionLink)(nil),                // 31: gru.v1.SessionLink
	(*AddSessionLinkRequest)(nil),      // 32: gru.v1.AddSessionLinkRequest
	(*ListSessionLinksRequest)(nil),    // 33: gru.v1.ListSessionLinksRequest
	(*ListSessionLinksResponse)(nil),   // 34: gru.v1.ListSessionLinksResponse
	(*DeleteSessionLinkRequest)(nil),   // 35: gru.v1.DeleteSessionLinkRequest
	(*DeleteSessionLinkResponse)(nil),  // 36: gru.v1.DeleteSessionLinkResponse
	(*timestamppb.Timestamp)(nil),      // 37: google.protobuf.Timestamp
}
var file_gru_v1_gru_proto_depIdxs = []int32{
	0,  // 0: gru.v1.Session.status:type_name -> gru.v1.SessionStatus
	37, // 1: gru.v1.Session.started_at:type_name -> google.protobuf.Timestamp
	37, // 2: gru.v1.Session.ended_at:type_name -> google.protobuf.Timestamp
	37, // 3: gru.v1.Session.last_event_at:type_name -> google.protobuf.Timestamp
	37, // 4: gru.v1.Project.created_at:type_name -> google.protobuf.Timestamp
	37, // 5: gru.v1.SessionEvent.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 6: gru.v1.ListSessionsRequest.status:type_name -> gru.v1.SessionStatus
	1,  // 7: gru.v1.ListSessionsResponse.sessions:type_name -> gru.v1.Session
	1,  // 8: gru.v1.LaunchSessionResponse.session:type_name -> gru.v1.Session
	2,  // 9: gru.v1.ListProjectsResponse.projects:type_name -> gru.v1.Project
	18, // 10: gru.v1.ListProfilesResponse.profiles:type_name -> gru.v1.AgentProfile
	37, // 11: gru.v1.Artifact.created_at:type_name -> google.protobuf.Timestamp
	26, // 12: gru.v1.ListArtifactsResponse.artifacts:type_name -> gru.v1.Artifact
	37, // 13: gru.v1.SessionLink.created_at:type_name -> google.protobuf.Timestamp
	31, // 14: gru.v1.ListSessionLinksResponse.links:type_name -> gru.v1.SessionLink
	4,  // 15: gru.v1.GruService.ListSessions:input_type -> gru.v1.ListSessionsRequest
	6,  // 16: gru.v1.GruService.GetSession:input_type -> gru.v1.GetSessionRequest
	7,  // 17: gru.v1.GruService.LaunchSession:input_type -> gru.v1.LaunchSessionRequest
	9,  // 18: gru.v1.GruService.KillSession:input_type -> gru.v1.KillSessionRequest
	11, // 19: gru.v1.GruService.DeleteSession:input_type -> gru.v1.DeleteSessionRequest
	13, // 20: gru.v1.GruService.PruneSessions:input_type -> gru.v1.PruneSessionsRequest
	21, // 21: gru.v1.GruService.SendInput:input_type -> gru.v1.SendInputRequest
	24, // 22: gru.v1.GruService.SuggestSessionName:input_type -> gru.v1.SuggestSessionNameRequest
	15, // 23: gru.v1.GruService.ListProjects:input_type -> gru.v1.ListProjectsRequest
	17, // 24: gru.v1.GruService.UpdateProject:input_type -> gru.v1.UpdateProjectRequest
	19, // 25: gru.v1.GruService.ListProfiles:input_type -> gru.v1.ListProfilesRequest
	27, // 26: gru.v1.GruService.ListArtifacts:input_type -> gru.v1.ListArtifactsRequest
	29, // 27: gru.v1.GruService.DeleteArtifact:input_type -> gru.v1.DeleteArtifactRequest
	32, // 28: gru.v1.GruService.AddSessionLink:input_type -> gru.v1.AddSessionLinkRequest
	33, // 29: gru.v1.GruService.ListSessionLinks:input_type -> gru.v1.ListSessionLinksRequest
	35, // 30: gru.v1.GruService.DeleteSessionLink:input_type -> gru.v1.DeleteSessionLinkRequest
	23, // 31: gru.v1.GruService.SubscribeEvents:input_type -> gru.v1.SubscribeEventsRequest
	5,  // 32: gru.v1.GruService.ListSessions:output_type -> gru.v1.ListSessionsResponse
	1,  // 33: gru.v1.GruService.GetSession:output_type -> gru.v1.Session
	8,  // 34: gru.v1.GruService.LaunchSession:output_type -> gru.v1.LaunchSessionResponse
	10, // 35: gru.v1.GruService.KillSession:output_type -> gru.v1.KillSessionResponse
	12, // 36: gru.v1.GruService.DeleteSession:output_type -> gru.v1.DeleteSessionResponse
	14, // 37: gru.v1.GruService.PruneSessions:output_type -> gru.v1.PruneSessionsResponse
	22, // 38: gru.v1.GruService.SendInput:output_type -> gru.v1.SendInputResponse
	25, // 39: gru.v1.GruService.SuggestSessionName:output_type -> gru.v1.SuggestSessionNameResponse
	16, // 40: gru.v1.GruService.ListProjects:output_type -> gru.v1.ListProjectsResponse
	2,  // 41: gru.v1.GruService.UpdateProject:output_type -> gru.v1.Project
	20, // 42: gru.v1.GruService.ListProfiles:output_type -> gru.v1.ListProfilesResponse
	28, // 43: gru.v1.GruService.ListArtifacts:output_type -> gru.v1.ListArtifactsResponse
	30, // 44: gru.v1.GruService.DeleteArtifact:output_type -> gru.v1.DeleteArtifactResponse
	31, // 45: gru.v1.GruService.AddSessionLink:output_type -> gru.v1.SessionLink
	34, // 46: gru.v1.GruService.ListSessionLinks:output_type -> gru.v1.ListSessionLinksResponse
	36, // 47: gru.v1.GruService.DeleteSessionLink:output_type -> gru.v1.DeleteSessionLinkResponse
	3,  // 48: gru.v1.GruService.SubscribeEvents:output_type -> gru.v1.SessionEvent
	32, // [32:49] is the sub-list for method output_type
	15, // [15:32] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_gru_v1_gru_proto_init() }
func file_gru_v1_gru_proto_init() {
	if File_gru_v1_gru_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gru_v1_gru_proto_rawDesc), len(file_gru_v1_gru_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gru_v1_gru_proto_goTypes,
		DependencyIndexes: file_gru_v1_gru_proto_depIdxs,
		EnumInfos:         file_gru_v1_gru_proto_enumTypes,
		MessageInfos:      file_gru_v1_gru_proto_msgTypes,
	}.Build()
	File_gru_v1_gru_proto = out.File
	file_gru_v1_gru_proto_goTypes = nil
	file_gru_v1_gru_proto_depIdxs = nil
}
