// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package db

import (
	"context"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (id, session_id, title, mime_type, size_bytes, token)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, session_id, title, mime_type, size_bytes, token, created_at
`

type CreateArtifactParams struct {
	ID        string
	SessionID string
	Title     string
	MimeType  string
	SizeBytes int64
	Token     string
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, createArtifact,
		arg.ID,
		arg.SessionID,
		arg.Title,
		arg.MimeType,
		arg.SizeBytes,
		arg.Token,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.Token,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArtifact = `-- name: DeleteArtifact :exec
DELETE FROM artifacts WHERE id = ?
`

func (q *Queries) DeleteArtifact(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteArtifact, id)
	return err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, session_id, title, mime_type, size_bytes, token, created_at FROM artifacts WHERE id = ? LIMIT 1
`

func (q *Queries) GetArtifact(ctx context.Context, id string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.Token,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactByToken = `-- name: GetArtifactByToken :one
SELECT id, session_id, title, mime_type, size_bytes, token, created_at FROM artifacts WHERE token = ? LIMIT 1
`

func (q *Queries) GetArtifactByToken(ctx context.Context, token string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByToken, token)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.Token,
		&i.CreatedAt,
	)
	return i, err
}

const listAllArtifactSessionDirs = `-- name: ListAllArtifactSessionDirs :many
SELECT DISTINCT session_id FROM artifacts
`

func (q *Queries) ListAllArtifactSessionDirs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllArtifactSessionDirs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var session_id string
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactIDsBySession = `-- name: ListArtifactIDsBySession :many
SELECT id FROM artifacts WHERE session_id = ?
`

func (q *Queries) ListArtifactIDsBySession(ctx context.Context, sessionID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactIDsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsBySession = `-- name: ListArtifactsBySession :many
SELECT id, session_id, title, mime_type, size_bytes, token, created_at FROM artifacts
WHERE session_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListArtifactsBySession(ctx context.Context, sessionID string) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Title,
			&i.MimeType,
			&i.SizeBytes,
			&i.Token,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumArtifactsForSession = `-- name: SumArtifactsForSession :one
SELECT
  COUNT(*)                                      AS count,
  CAST(COALESCE(SUM(size_bytes), 0) AS INTEGER) AS bytes_used
FROM artifacts
WHERE session_id = ?
`

type SumArtifactsForSessionRow struct {
	Count     int64
	BytesUsed int64
}

func (q *Queries) SumArtifactsForSession(ctx context.Context, sessionID string) (SumArtifactsForSessionRow, error) {
	row := q.db.QueryRowContext(ctx, sumArtifactsForSession, sessionID)
	var i SumArtifactsForSessionRow
	err := row.Scan(&i.Count, &i.BytesUsed)
	return i, err
}
