// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package db

import (
	"context"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, label, push_endpoint, push_p256dh, push_auth, action_token_secret)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, label, push_endpoint, push_p256dh, push_auth, action_token_secret, created_at, last_seen_at, stale
`

type CreateDeviceParams struct {
	ID                string
	Label             string
	PushEndpoint      string
	PushP256dh        string
	PushAuth          string
	ActionTokenSecret string
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice,
		arg.ID,
		arg.Label,
		arg.PushEndpoint,
		arg.PushP256dh,
		arg.PushAuth,
		arg.ActionTokenSecret,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.PushEndpoint,
		&i.PushP256dh,
		&i.PushAuth,
		&i.ActionTokenSecret,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.Stale,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, id)
	return err
}

const getAction = `-- name: GetAction :one
SELECT event_id, "action", device_id, resolved_at FROM action_log WHERE event_id = ? AND action = ? LIMIT 1
`

type GetActionParams struct {
	EventID string
	Action  string
}

func (q *Queries) GetAction(ctx context.Context, arg GetActionParams) (ActionLog, error) {
	row := q.db.QueryRowContext(ctx, getAction, arg.EventID, arg.Action)
	var i ActionLog
	err := row.Scan(
		&i.EventID,
		&i.Action,
		&i.DeviceID,
		&i.ResolvedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, label, push_endpoint, push_p256dh, push_auth, action_token_secret, created_at, last_seen_at, stale FROM devices WHERE id = ? LIMIT 1
`

func (q *Queries) GetDevice(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.PushEndpoint,
		&i.PushP256dh,
		&i.PushAuth,
		&i.ActionTokenSecret,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.Stale,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, label, push_endpoint, push_p256dh, push_auth, action_token_secret, created_at, last_seen_at, stale FROM devices WHERE stale = 0 ORDER BY created_at ASC
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.PushEndpoint,
			&i.PushP256dh,
			&i.PushAuth,
			&i.ActionTokenSecret,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.Stale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeviceStale = `-- name: MarkDeviceStale :exec
UPDATE devices SET stale = 1 WHERE id = ?
`

func (q *Queries) MarkDeviceStale(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markDeviceStale, id)
	return err
}

const recordAction = `-- name: RecordAction :exec
INSERT INTO action_log (event_id, action, device_id)
VALUES (?, ?, ?)
`

type RecordActionParams struct {
	EventID  string
	Action   string
	DeviceID string
}

func (q *Queries) RecordAction(ctx context.Context, arg RecordActionParams) error {
	_, err := q.db.ExecContext(ctx, recordAction, arg.EventID, arg.Action, arg.DeviceID)
	return err
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE devices SET last_seen_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

func (q *Queries) TouchDevice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchDevice, id)
	return err
}

const updateDeviceSubscription = `-- name: UpdateDeviceSubscription :one
UPDATE devices
SET push_endpoint = ?1,
    push_p256dh   = ?2,
    push_auth     = ?3,
    last_seen_at  = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?4
RETURNING id, label, push_endpoint, push_p256dh, push_auth, action_token_secret, created_at, last_seen_at, stale
`

type UpdateDeviceSubscriptionParams struct {
	PushEndpoint string
	PushP256dh   string
	PushAuth     string
	ID           string
}

func (q *Queries) UpdateDeviceSubscription(ctx context.Context, arg UpdateDeviceSubscriptionParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, updateDeviceSubscription,
		arg.PushEndpoint,
		arg.PushP256dh,
		arg.PushAuth,
		arg.ID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.PushEndpoint,
		&i.PushP256dh,
		&i.PushAuth,
		&i.ActionTokenSecret,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.Stale,
	)
	return i, err
}
