// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, session_id, project_id, runtime, type, timestamp, payload)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, session_id, project_id, runtime, type, timestamp, payload, created_at
`

type CreateEventParams struct {
	ID        string
	SessionID string
	ProjectID string
	Runtime   string
	Type      string
	Timestamp string
	Payload   string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.ID,
		arg.SessionID,
		arg.ProjectID,
		arg.Runtime,
		arg.Type,
		arg.Timestamp,
		arg.Payload,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ProjectID,
		&i.Runtime,
		&i.Type,
		&i.Timestamp,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestEventForSession = `-- name: GetLatestEventForSession :one
SELECT id, session_id, project_id, runtime, type, timestamp, payload, created_at FROM events
WHERE session_id = ?
ORDER BY timestamp DESC
LIMIT 1
`

func (q *Queries) GetLatestEventForSession(ctx context.Context, sessionID string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getLatestEventForSession, sessionID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ProjectID,
		&i.Runtime,
		&i.Type,
		&i.Timestamp,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listEventsBySession = `-- name: ListEventsBySession :many
SELECT id, session_id, project_id, runtime, type, timestamp, payload, created_at FROM events
WHERE session_id = ?
ORDER BY timestamp ASC
`

func (q *Queries) ListEventsBySession(ctx context.Context, sessionID string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ProjectID,
			&i.Runtime,
			&i.Type,
			&i.Timestamp,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
