// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Event struct {
	ID        string
	SessionID string
	ProjectID string
	Runtime   string
	Type      string
	Timestamp string
	Payload   string
	CreatedAt string
}

type Project struct {
	ID        string
	Name      string
	Path      string
	Runtime   string
	CreatedAt string
}

type SchemaMigration struct {
	Version   int64
	AppliedAt string
}

type Session struct {
	ID             string
	ProjectID      string
	Runtime        string
	Status         string
	Profile        *string
	Pid            *int64
	Pgid           *int64
	AttentionScore float64
	StartedAt      string
	EndedAt        *string
	LastEventAt    *string
	TmuxSession    *string
	TmuxWindow     *string
	Name           string
	Description    string
	Prompt         string
}
