// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
)

const getProject = `-- name: GetProject :one
SELECT id, name, adapter, runtime, created_at FROM projects WHERE id = ? LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Adapter,
		&i.Runtime,
		&i.CreatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, adapter, runtime, created_at FROM projects ORDER BY name ASC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Adapter,
			&i.Runtime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameProject = `-- name: RenameProject :one
UPDATE projects
SET name = ?1
WHERE id = ?2
RETURNING id, name, adapter, runtime, created_at
`

type RenameProjectParams struct {
	Name string
	ID   string
}

func (q *Queries) RenameProject(ctx context.Context, arg RenameProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, renameProject, arg.Name, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Adapter,
		&i.Runtime,
		&i.CreatedAt,
	)
	return i, err
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (id, name, adapter, runtime)
VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name    = excluded.name,
    adapter = excluded.adapter,
    runtime = excluded.runtime
RETURNING id, name, adapter, runtime, created_at
`

type UpsertProjectParams struct {
	ID      string
	Name    string
	Adapter string
	Runtime string
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, upsertProject,
		arg.ID,
		arg.Name,
		arg.Adapter,
		arg.Runtime,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Adapter,
		&i.Runtime,
		&i.CreatedAt,
	)
	return i, err
}
