// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	GetJournalSession(ctx context.Context) (Session, error)
	GetLatestEventForSession(ctx context.Context, sessionID string) (Event, error)
	GetProject(ctx context.Context, id string) (Project, error)
	GetProjectByPath(ctx context.Context, path string) (Project, error)
	GetSession(ctx context.Context, id string) (Session, error)
	ListEventsBySession(ctx context.Context, sessionID string) ([]Event, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error)
	UpdateProjectAdditionalWorkdirs(ctx context.Context, arg UpdateProjectAdditionalWorkdirsParams) (Project, error)
	UpdateSessionAttentionScore(ctx context.Context, arg UpdateSessionAttentionScoreParams) (Session, error)
	UpdateSessionLastEvent(ctx context.Context, arg UpdateSessionLastEventParams) error
	UpdateSessionPID(ctx context.Context, arg UpdateSessionPIDParams) error
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (Session, error)
	UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error)
}

var _ Querier = (*Queries)(nil)
