// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_links.sql

package db

import (
	"context"
)

const countSessionLinksForSession = `-- name: CountSessionLinksForSession :one
SELECT COUNT(*) AS count FROM session_links WHERE session_id = ?
`

func (q *Queries) CountSessionLinksForSession(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionLinksForSession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSessionLink = `-- name: CreateSessionLink :one
INSERT INTO session_links (id, session_id, title, url)
VALUES (?, ?, ?, ?)
RETURNING id, session_id, title, url, created_at
`

type CreateSessionLinkParams struct {
	ID        string
	SessionID string
	Title     string
	Url       string
}

func (q *Queries) CreateSessionLink(ctx context.Context, arg CreateSessionLinkParams) (SessionLink, error) {
	row := q.db.QueryRowContext(ctx, createSessionLink,
		arg.ID,
		arg.SessionID,
		arg.Title,
		arg.Url,
	)
	var i SessionLink
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Title,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSessionLink = `-- name: DeleteSessionLink :exec
DELETE FROM session_links WHERE id = ?
`

func (q *Queries) DeleteSessionLink(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionLink, id)
	return err
}

const getSessionLink = `-- name: GetSessionLink :one
SELECT id, session_id, title, url, created_at FROM session_links WHERE id = ? LIMIT 1
`

func (q *Queries) GetSessionLink(ctx context.Context, id string) (SessionLink, error) {
	row := q.db.QueryRowContext(ctx, getSessionLink, id)
	var i SessionLink
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Title,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const listSessionLinksBySession = `-- name: ListSessionLinksBySession :many
SELECT id, session_id, title, url, created_at FROM session_links
WHERE session_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListSessionLinksBySession(ctx context.Context, sessionID string) ([]SessionLink, error) {
	rows, err := q.db.QueryContext(ctx, listSessionLinksBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionLink{}
	for rows.Next() {
		var i SessionLink
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Title,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
