// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, project_id, runtime, status, profile, pid, pgid, tmux_session, tmux_window)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, runtime, status, profile, pid, pgid, attention_score, started_at, ended_at, last_event_at, tmux_session, tmux_window
`

type CreateSessionParams struct {
	ID          string
	ProjectID   string
	Runtime     string
	Status      string
	Profile     *string
	Pid         *int64
	Pgid        *int64
	TmuxSession *string
	TmuxWindow  *string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.ProjectID,
		arg.Runtime,
		arg.Status,
		arg.Profile,
		arg.Pid,
		arg.Pgid,
		arg.TmuxSession,
		arg.TmuxWindow,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Runtime,
		&i.Status,
		&i.Profile,
		&i.Pid,
		&i.Pgid,
		&i.AttentionScore,
		&i.StartedAt,
		&i.EndedAt,
		&i.LastEventAt,
		&i.TmuxSession,
		&i.TmuxWindow,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, project_id, runtime, status, profile, pid, pgid, attention_score, started_at, ended_at, last_event_at, tmux_session, tmux_window FROM sessions WHERE id = ? LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Runtime,
		&i.Status,
		&i.Profile,
		&i.Pid,
		&i.Pgid,
		&i.AttentionScore,
		&i.StartedAt,
		&i.EndedAt,
		&i.LastEventAt,
		&i.TmuxSession,
		&i.TmuxWindow,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, project_id, runtime, status, profile, pid, pgid, attention_score, started_at, ended_at, last_event_at, tmux_session, tmux_window FROM sessions
WHERE project_id = COALESCE(NULLIF(?1, ''), project_id)
  AND status = COALESCE(NULLIF(?2, ''), status)
ORDER BY started_at DESC
`

type ListSessionsParams struct {
	ProjectID interface{}
	Status    interface{}
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Runtime,
			&i.Status,
			&i.Profile,
			&i.Pid,
			&i.Pgid,
			&i.AttentionScore,
			&i.StartedAt,
			&i.EndedAt,
			&i.LastEventAt,
			&i.TmuxSession,
			&i.TmuxWindow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionLastEvent = `-- name: UpdateSessionLastEvent :exec
UPDATE sessions
SET status = ?,
    last_event_at = ?,
    attention_score = ?
WHERE id = ?
`

type UpdateSessionLastEventParams struct {
	Status         string
	LastEventAt    *string
	AttentionScore float64
	ID             string
}

func (q *Queries) UpdateSessionLastEvent(ctx context.Context, arg UpdateSessionLastEventParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionLastEvent,
		arg.Status,
		arg.LastEventAt,
		arg.AttentionScore,
		arg.ID,
	)
	return err
}

const updateSessionPID = `-- name: UpdateSessionPID :exec
UPDATE sessions SET pid = ?, pgid = ? WHERE id = ?
`

type UpdateSessionPIDParams struct {
	Pid  *int64
	Pgid *int64
	ID   string
}

func (q *Queries) UpdateSessionPID(ctx context.Context, arg UpdateSessionPIDParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionPID, arg.Pid, arg.Pgid, arg.ID)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :one
UPDATE sessions
SET status = ?1,
    ended_at = CASE WHEN sqlc.arg(status) IN ('completed','errored','killed') THEN strftime('%Y-%m-%dT%H:%M:%SZ','now') ELSE ended_at END
WHERE id = ?2
RETURNING id, project_id, runtime, status, profile, pid, pgid, attention_score, started_at, ended_at, last_event_at, tmux_session, tmux_window
`

type UpdateSessionStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSessionStatus, arg.Status, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Runtime,
		&i.Status,
		&i.Profile,
		&i.Pid,
		&i.Pgid,
		&i.AttentionScore,
		&i.StartedAt,
		&i.EndedAt,
		&i.LastEventAt,
		&i.TmuxSession,
		&i.TmuxWindow,
	)
	return i, err
}
