// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, project_id, runtime, status, profile, pid, pgid, tmux_session, tmux_window, name, description, prompt, role)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, runtime, status, profile, pid, pgid, attention_score, started_at, ended_at, last_event_at, tmux_session, tmux_window, name, description, prompt, role
`

type CreateSessionParams struct {
	ID          string
	ProjectID   string
	Runtime     string
	Status      string
	Profile     *string
	Pid         *int64
	Pgid        *int64
	TmuxSession *string
	TmuxWindow  *string
	Name        string
	Description string
	Prompt      string
	Role        string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.ProjectID,
		arg.Runtime,
		arg.Status,
		arg.Profile,
		arg.Pid,
		arg.Pgid,
		arg.TmuxSession,
		arg.TmuxWindow,
		arg.Name,
		arg.Description,
		arg.Prompt,
		arg.Role,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Runtime,
		&i.Status,
		&i.Profile,
		&i.Pid,
		&i.Pgid,
		&i.AttentionScore,
		&i.StartedAt,
		&i.EndedAt,
		&i.LastEventAt,
		&i.TmuxSession,
		&i.TmuxWindow,
		&i.Name,
		&i.Description,
		&i.Prompt,
		&i.Role,
	)
	return i, err
}

const deleteEventsForSession = `-- name: DeleteEventsForSession :exec
DELETE FROM events WHERE session_id = ?1
`

func (q *Queries) DeleteEventsForSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEventsForSession, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getAssistantSession = `-- name: GetAssistantSession :one
SELECT id, project_id, runtime, status, profile, pid, pgid, attention_score, started_at, ended_at, last_event_at, tmux_session, tmux_window, name, description, prompt, role FROM sessions
WHERE role = 'assistant'
  AND status IN ('starting','running','idle','needs_attention')
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetAssistantSession(ctx context.Context) (Session, error) {
	row := q.db.QueryRowContext(ctx, getAssistantSession)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Runtime,
		&i.Status,
		&i.Profile,
		&i.Pid,
		&i.Pgid,
		&i.AttentionScore,
		&i.StartedAt,
		&i.EndedAt,
		&i.LastEventAt,
		&i.TmuxSession,
		&i.TmuxWindow,
		&i.Name,
		&i.Description,
		&i.Prompt,
		&i.Role,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, project_id, runtime, status, profile, pid, pgid, attention_score, started_at, ended_at, last_event_at, tmux_session, tmux_window, name, description, prompt, role FROM sessions WHERE id = ? LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Runtime,
		&i.Status,
		&i.Profile,
		&i.Pid,
		&i.Pgid,
		&i.AttentionScore,
		&i.StartedAt,
		&i.EndedAt,
		&i.LastEventAt,
		&i.TmuxSession,
		&i.TmuxWindow,
		&i.Name,
		&i.Description,
		&i.Prompt,
		&i.Role,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, project_id, runtime, status, profile, pid, pgid, attention_score, started_at, ended_at, last_event_at, tmux_session, tmux_window, name, description, prompt, role FROM sessions
WHERE project_id = COALESCE(NULLIF(?1, ''), project_id)
  AND status = COALESCE(NULLIF(?2, ''), status)
ORDER BY started_at DESC
`

type ListSessionsParams struct {
	ProjectID interface{}
	Status    interface{}
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Runtime,
			&i.Status,
			&i.Profile,
			&i.Pid,
			&i.Pgid,
			&i.AttentionScore,
			&i.StartedAt,
			&i.EndedAt,
			&i.LastEventAt,
			&i.TmuxSession,
			&i.TmuxWindow,
			&i.Name,
			&i.Description,
			&i.Prompt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerminalSessionIDs = `-- name: ListTerminalSessionIDs :many
SELECT id FROM sessions
WHERE status IN ('completed','errored','killed')
  AND role <> 'assistant'
`

// Returns IDs of every terminal (completed/errored/killed) session, skipping
// assistant-role singletons. Used by PruneSessions to delete in a single
// atomic loop without an extra ListSessions round-trip.
func (q *Queries) ListTerminalSessionIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTerminalSessionIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionAttentionScore = `-- name: UpdateSessionAttentionScore :one
UPDATE sessions
SET attention_score = ?1
WHERE id = ?2
RETURNING id, project_id, runtime, status, profile, pid, pgid, attention_score, started_at, ended_at, last_event_at, tmux_session, tmux_window, name, description, prompt, role
`

type UpdateSessionAttentionScoreParams struct {
	AttentionScore float64
	ID             string
}

func (q *Queries) UpdateSessionAttentionScore(ctx context.Context, arg UpdateSessionAttentionScoreParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSessionAttentionScore, arg.AttentionScore, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Runtime,
		&i.Status,
		&i.Profile,
		&i.Pid,
		&i.Pgid,
		&i.AttentionScore,
		&i.StartedAt,
		&i.EndedAt,
		&i.LastEventAt,
		&i.TmuxSession,
		&i.TmuxWindow,
		&i.Name,
		&i.Description,
		&i.Prompt,
		&i.Role,
	)
	return i, err
}

const updateSessionLastEvent = `-- name: UpdateSessionLastEvent :exec
UPDATE sessions
SET status = ?,
    last_event_at = ?,
    attention_score = ?
WHERE id = ?
`

type UpdateSessionLastEventParams struct {
	Status         string
	LastEventAt    *string
	AttentionScore float64
	ID             string
}

func (q *Queries) UpdateSessionLastEvent(ctx context.Context, arg UpdateSessionLastEventParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionLastEvent,
		arg.Status,
		arg.LastEventAt,
		arg.AttentionScore,
		arg.ID,
	)
	return err
}

const updateSessionPID = `-- name: UpdateSessionPID :exec
UPDATE sessions SET pid = ?, pgid = ? WHERE id = ?
`

type UpdateSessionPIDParams struct {
	Pid  *int64
	Pgid *int64
	ID   string
}

func (q *Queries) UpdateSessionPID(ctx context.Context, arg UpdateSessionPIDParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionPID, arg.Pid, arg.Pgid, arg.ID)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :one
UPDATE sessions
SET status   = ?1,
    ended_at = COALESCE(ended_at, ?2)
WHERE id = ?3
RETURNING id, project_id, runtime, status, profile, pid, pgid, attention_score, started_at, ended_at, last_event_at, tmux_session, tmux_window, name, description, prompt, role
`

type UpdateSessionStatusParams struct {
	Status  string
	EndedAt *string
	ID      string
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSessionStatus, arg.Status, arg.EndedAt, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Runtime,
		&i.Status,
		&i.Profile,
		&i.Pid,
		&i.Pgid,
		&i.AttentionScore,
		&i.StartedAt,
		&i.EndedAt,
		&i.LastEventAt,
		&i.TmuxSession,
		&i.TmuxWindow,
		&i.Name,
		&i.Description,
		&i.Prompt,
		&i.Role,
	)
	return i, err
}
